#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_dholoTYPE                   130
#define ID_IMAGE_PANEL                  131
#define IDS_EXPLORER                    132
#define IDS_CONVERTER                   133
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_EXPLORER                    310
#define IDR_MENU1                       312
#define IDR_MENU2                       313
#define IDR_IDR_POPUP_IMAGE_LIST1       314
#define IDR_POPUP_EXPLORER              315
#define IDD_DIALOG_CREATE_WINDOW        316
#define IDC_OPENCL_PLATFORM_INFO        1008
#define IDC_STATIC_PLATFORM_NAME        1009
#define IDC_COMBO_PLATFROMS             1010
#define IDC_EDIT_PLATFORM_VENDOR        1011
#define IDC_STATIC_PLATFORM_VENDOR      1012
#define IDC_STATIC_PLATFORM_EXTENSIONS  1013
#define IDC_COMBO_PLATFORM_EXTENSIONS   1014
#define IDC_LABEL_PLATFORM_VERSION      1015
#define IDC_STATIC_DEVICE_NAME          1016
#define IDC_COMBO_DEVICE                1017
#define IDC_EDIT_PLATFORM_VERSION       1018
#define IDC_EDIT_DEVICE_VENDOR          1019
#define IDC_STATIC_DEVICE_VENDOR        1020
#define IDC_STATIC_DEVICE               1021
#define IDC_STATIC_DEVICE_EXTENSIONS    1022
#define IDC_LABEL_DEVICE_VERSION        1024
#define IDC_EDIT_DEVICE_VERSION         1025
#define IDC_LIST_PLATFORM_EXTENSIONS    1026
#define IDC_LIST_DEVICE_EXTENSIONS      1027
#define IDC_BUTTON1                     1029
#define IDC_BUTTON_BY_DEFAULT           1029
#define IDC_BUTTON2                     1030
#define IDC_EDIT_GLOBAL_SIZE_H          1031
#define IDC_EDIT_GLOBAL_SIZE_W          1032
#define IDC_EDIT3                       1033
#define IDC_EDIT_LOCAL_SIZE_H           1033
#define IDC_EDIT_LOCAL_SIZE_W           1034
#define IDC_WORK_SETTINGS               1035
#define IDC_STATIC_GLOBAL_SIZE          1036
#define IDC_STATIC_LOCAL_SIZE           1037
#define IDC_EDIT1                       1038
#define IDC_EDIT_DEVICE_TYPE            1038
#define IDC_STATIC_DEVICE_TYPE          1039
#define ID_ADD_IMAGE                    32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_LOAD_IMAGE                   32778
#define ID_DELETE_IMAGE                 32779
#define ID_32780                        32780
#define ID_PROPERTIES                   32781
#define ID_CUT_IMAGE                    32784
#define ID_LOAD_IMG                     32789
#define ID_SELECT_IMAGE                 32790
#define ID_LOAD_INTO_GP                 32792
#define ID_SHOW_IMAGE                   32793
#define IDS_IMAGE_LIST_COLUMN_IMAGE     62000
#define IDS_IMAGE_LIST_COLUMN_PATH      62001
#define IDS_IMAGE_LIST                  62002
#define IDR_POPUP_CONVERTER             62003
#define ID_CONVERT_IMAGE                62004
#define IDS_IMG_CONVERTER               62005
#define ID_EDIT_SAVE                    62003
#define ID_TEST                         62004

#define ERR_CODE_DEVICE_NOT_FOUND															1
#define ERR_CODE_DEVICE_NOT_AVAILABLE														2
#define ERR_CODE_COMPILER_NOT_AVAILABLE														3
#define ERR_CODE_MEM_OBJECT_ALLOCATION_FAILURE												4
#define ERR_CODE_OUT_OF_RESOURCES															5
#define ERR_CODE_OUT_OF_HOST_MEMORY															6
#define ERR_CODE_PROFILING_INFO_NOT_AVAILABLE												7
#define ERR_CODE_MEM_COPY_OVERLAP															8
#define ERR_CODE_IMAGE_FORMAT_MISMATCH														9
#define ERR_CODE_IMAGE_FORMAT_NOT_SUPPORTED													10
#define ERR_CODE_BUILD_PROGRAM_FAILURE														11
#define ERR_CODE_MAP_FAILURE																12
#define ERR_CODE_MISALIGNED_SUB_BUFFER_OFFSET												13
#define ERR_CODE_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST									14
#define ERR_CODE_COMPILE_PROGRAM_FAILURE													15
#define ERR_CODE_LINKER_NOT_AVAILABLE														16
#define ERR_CODE_LINK_PROGRAM_FAILURE														17
#define ERR_CODE_DEVICE_PARTITION_FAILED													18
#define ERR_CODE_KERNEL_ARG_INFO_NOT_AVAILABLE												19
#define ERR_CODE_INVALID_VALUE																30
#define ERR_CODE_INVALID_DEVICE_TYPE														31
#define ERR_CODE_INVALID_PLATFORM															32
#define ERR_CODE_INVALID_DEVICE																33
#define ERR_CODE_INVALID_CONTEXT															34
#define ERR_CODE_INVALID_QUEUE_PROPERTIES													35
#define ERR_CODE_INVALID_COMMAND_QUEUE														36
#define ERR_CODE_INVALID_HOST_PTR															37
#define ERR_CODE_INVALID_MEM_OBJECT															38
#define ERR_CODE_INVALID_IMAGE_FORMAT_DESCRIPTOR											39
#define ERR_CODE_INVALID_IMAGE_SIZE															40
#define ERR_CODE_INVALID_SAMPLER															41
#define ERR_CODE_INVALID_BINARY																42
#define ERR_CODE_INVALID_BUILD_OPTIONS														43
#define ERR_CODE_INVALID_PROGRAM															44
#define ERR_CODE_INVALID_PROGRAM_EXECUTABLE													45
#define ERR_CODE_INVALID_KERNEL_NAME														46
#define ERR_CODE_INVALID_KERNEL_DEFINITION													47
#define ERR_CODE_INVALID_KERNEL																48
#define ERR_CODE_INVALID_ARG_INDEX															49
#define ERR_CODE_INVALID_ARG_VALUE															50
#define ERR_CODE_INVALID_ARG_SIZE															51
#define ERR_CODE_INVALID_KERNEL_ARGS														52
#define ERR_CODE_INVALID_WORK_DIMENSION														53
#define ERR_CODE_INVALID_WORK_GROUP_SIZE													54
#define ERR_CODE_INVALID_WORK_ITEM_SIZE														55
#define ERR_CODE_INVALID_GLOBAL_OFFSET														56
#define ERR_CODE_INVALID_EVENT_WAIT_LIST													57
#define ERR_CODE_INVALID_EVENT																58
#define ERR_CODE_INVALID_OPERATION															59
#define ERR_CODE_INVALID_GL_OBJECT															60
#define ERR_CODE_INVALID_BUFFER_SIZE														61
#define ERR_CODE_INVALID_MIP_LEVEL															62
#define ERR_CODE_INVALID_GLOBAL_WORK_SIZE													63
#define ERR_CODE_INVALID_PROPERTY															64
#define ERR_CODE_INVALID_IMAGE_DESCRIPTOR													65
#define ERR_CODE_INVALID_COMPILER_OPTIONS													66
#define ERR_CODE_INVALID_LINKER_OPTIONS														67
#define ERR_CODE_INVALID_DEVICE_PARTITION_COUNT												68
#define ERR_CODE_INVALID_PIPE_SIZE															69
#define ERR_CODE_INVALID_DEVICE_QUEUE														70
#define ERR_CODE_INVALID_GL_SHAREGROUP_REFERENCE_KHR										1000
#define ERR_CODE_PLATFORM_NOT_FOUND_KHR														1001
#define ERR_CODE_INVALID_D3D10_DEVICE_KHR													1002
#define ERR_CODE_INVALID_D3D10_RESOURCE_KHR													1003
#define ERR_CODE_D3D10_RESOURCE_ALREADY_ACQUIRED_KHR										1004
#define ERR_CODE_D3D10_RESOURCE_NOT_ACQUIRED_KHR											1005
#define ERR_CODE_INVALID_D3D11_DEVICE_KHR													1006
#define ERR_CODE_INVALID_D3D11_RESOURCE_KHR													1007
#define ERR_CODE_D3D11_RESOURCE_ALREADY_ACQUIRED_KHR										1008
#define ERR_CODE_D3D11_RESOURCE_NOT_ACQUIRED_KHR											1009
#define ERR_CODE_INVALID_D3D9_DEVICE_NV_CL_INVALID_DX9_DEVICE_INTEL							1010
#define ERR_CODE_INVALID_D3D9_RESOURCE_NV_CL_INVALID_DX9_RESOURCE_INTEL						1011
#define ERR_CODE_D3D9_RESOURCE_ALREADY_ACQUIRED_NV_CL_DX9_RESOURCE_ALREADY_ACQUIRED_INTEL	1012
#define ERR_CODE_D3D9_RESOURCE_NOT_ACQUIRED_NV_CL_DX9_RESOURCE_NOT_ACQUIRED_INTEL			1013
#define ERR_CODE_EGL_RESOURCE_NOT_ACQUIRED_KHR												1092
#define ERR_CODE_INVALID_EGL_OBJECT_KHR														1093
#define ERR_CODE_INVALID_ACCELERATOR_INTEL													1094
#define ERR_CODE_INVALID_ACCELERATOR_TYPE_INTEL												1095
#define ERR_CODE_INVALID_ACCELERATOR_DESCRIPTOR_INTEL										1096
#define ERR_CODE_ACCELERATOR_TYPE_NOT_SUPPORTED_INTEL										1097
#define ERR_CODE_INVALID_VA_API_MEDIA_ADAPTER_INTEL											1098
#define ERR_CODE_INVALID_VA_API_MEDIA_SURFACE_INTEL											1099
#define ERR_CODE_VA_API_MEDIA_SURFACE_ALREADY_ACQUIRED_INTEL								1100
#define ERR_CODE_VA_API_MEDIA_SURFACE_NOT_ACQUIRED_INTEL									1101
#define ERR_CODE_NVIDIA																		9999
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
